/* Generated by Together */

package impl.miw.business.bookmanager;

import java.util.ArrayList;
import java.util.Map;
import java.util.Vector;

import org.springframework.beans.factory.annotation.Autowired;

import com.miw.business.BookManagerService;
import com.miw.model.Book;
import com.miw.model.Iva;
import com.miw.persistence.BookDataService;
import com.miw.persistence.IvaDataService;

public class BookManager implements BookManagerService {

	@Autowired
	private BookDataService bookDataService = null;
	@Autowired
	private IvaDataService ivaDataService = null;
	private Map<Integer, Integer> discounts = null;

	public void setDiscounts(Map<Integer, Integer> discounts) {
		this.discounts = discounts;
	}

	public void setBookDataService(BookDataService bookDataService) {
		System.out.println("Setting bookDataService bean");
		this.bookDataService = bookDataService;
	}

	public void setIvaDataService(IvaDataService ivaDataService) {
		System.out.println("Setting ivaDataService bean");
		this.ivaDataService = ivaDataService;
	}

	public Vector<Book> getBooks() throws Exception {

		Vector<Book> books = bookDataService.getBooks();
		Vector<Iva> ivas = ivaDataService.getIvas();
		for (Book book : books) {
			for (Iva iva : ivas) {
				if (book.getFamily() == iva.getFamily()) {
					book.setPrice(book.getBasePrice() * iva.getValue());
				}
			}
		}
		return books;
	}

	public ArrayList<Book> getSpecialOffer() throws Exception {
		ArrayList<Book> onSale = new ArrayList<Book>();

		if (discounts != null) {
			for (Book b : getBooks()) {
				for (Integer type : discounts.keySet()) {
					if (b.getFamily() == type) {
						System.out.println("Applying disccount to " + b.getTitle());
						b.setPrice((double) b.getPrice() * discounts.get(type));
						onSale.add(b);
					}
				}
			}
		}

		return onSale;
	}
	
	public Book newBook(Book book) throws Exception {
		// TODO Auto-generated method stub
		return this.bookDataService.newBook(book);
	}
}
